# Generated by Django 5.1.2 on 2024-10-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escultor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=255)),
                ('tematica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionEscultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escultor.escultor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='escultores',
            field=models.ManyToManyField(related_name='eventos_escultores', through='evento.ParticipacionEscultor', to='escultor.escultor'),
        ),
        migrations.AddConstraint(
            model_name='participacionescultor',
            constraint=models.UniqueConstraint(fields=('evento', 'escultor'), name='unique_escultor_por_evento'),
        ),
    ]
