# Generated by Django 5.1.2 on 2024-10-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=255)),
                ('tematica', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
