# Generated by Django 5.1.2 on 2024-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escultor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('biografia', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
