# Generated by Django 5.1.2 on 2024-10-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('biografia', models.CharField(max_length=255, null=True)),
                ('contacto', models.CharField(max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
